import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import getTest from "@/pages/api/backend";
import {useState, useEffect} from "react";

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
    const [data, setData] = useState("Hello World");


    useEffect(() => {
        fetch('http://localhost:8080/')
            .then(response => response.json())
            .then(data => setData(data.message))
            .catch(error => console.log(error));
    }, []);

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className = "text-2xl font-bold">
            {data}
        </h1>
      </main>
    </>
  )
}
